# Generated by Django 4.1.1 on 2022-09-30 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0003_category_category_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField()),
                ('desc', models.TextField(max_length=100, null=True)),
                ('product_image', models.ImageField(null=True, upload_to='upload/product/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eshop.category')),
            ],
        ),
    ]
