# Generated by Django 4.1.1 on 2022-09-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0004_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
