# Generated by Django 4.1.1 on 2022-09-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0005_rename_product_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
