# Generated by Django 4.1.1 on 2022-10-11 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Eshop", "0008_order_dtls_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order_dtls", old_name="desc", new_name="mobile",
        ),
    ]
