# Generated by Django 4.1.1 on 2022-10-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Eshop", "0009_rename_desc_order_dtls_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_dtls",
            name="price",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
